### PR TITLE
Update runtime to 20.08

### PR DESCRIPTION
**Pull request by soredake**
Maybe it will fix https://github.com/flathub/com.github.vladimiry.ElectronMail/issues/1

### CODE REVIEW

**Comment by vladimiry** [comment]
Closing since build failed. I'm going to try 20.08 runtime stack when will be preparing v4.9.0 release (currently blocked by unresolved proton's issue, see details in https://github.com/vladimiry/ElectronMail/issues/332).

**Comment by vladimiry** [comment]
@soredake you can try v4.8.0 built on 20.08 environment by running `flatpak install --user https://dl.flathub.org/build-repo/30054/com.github.vladimiry.ElectronMail.flatpakref`. It's the version assembled from https://github.com/flathub/com.github.vladimiry.ElectronMail/commits/beta.

**Comment by soredake** [comment]
```
error: Can't load uri https://dl.flathub.org/build-repo/30054/com.github.vladimiry.ElectronMail.flatpakref: Server returned status 404: Not Found
```
I tried flatpak install https://flathub.org/beta-repo/appstream/com.github.vladimiry.ElectronMail.flatpakref, still unable to use keepassxc as secrets provider

**Comment by vladimiry** [comment]
`flatpak install --user https://dl.flathub.org/build-repo/30054/com.github.vladimiry.ElectronMail.flatpakref` still works for me. But you can also (local package assembling and start):
- checkout https://github.com/flathub/com.github.vladimiry.ElectronMail/commits/beta and 
- run `flatpak-builder --force-clean --repo=repo --user --install build-dir com.github.vladimiry.ElectronMail.json`
- run `flatpak run com.github.vladimiry.ElectronMail`

**Comment by soredake** [comment]
Same, time to report this to https://github.com/atom/node-keytar :(

**Comment by vladimiry** [comment]
Of course you can report. But again, it works for me. So it's system-dependent issue. Besides, they will likely ask for minimal reproducible project, not the ElectronMail.

**Pull request closed without merging**
